version: "3.7"

volumes:
  db_volume:


services:

  mssql-server:
    image: mcr.microsoft.com/mssql/server:latest
    restart: always
    volumes: 
      - db_volume:/var/opt/mssql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Alizar457
      - MSSQL_TCP_PORT=1433
    ports:
      - "1433:1433"

  flask:
    build: ./flask
    restart: always
    environment:
      - APP_NAME=FL Planetary
    expose:
      - 5000

  django:
    build: ./django
    restart: always
    environment:
      - DJ_APP_NAME=DJ Planetary
    expose:
      - 8000

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - mssql-server
      - flask
      - django